(()=>{'use strict';
const KEYSETS={major:[{tonic:'C',scale:['C','D','E','F','G','A','B']},{tonic:'G',scale:['G','A','B','C','D','E','F#']},{tonic:'D',scale:['D','E','F#','G','A','B','C#']},{tonic:'A',scale:['A','B','C#','D','E','F#','G#']},{tonic:'E',scale:['E','F#','G#','A','B','C#','D#']},{tonic:'B',scale:['B','C#','D#','E','F#','G#','A#']},{tonic:'F#',scale:['F#','G#','A#','B','C#','D#','E#']},{tonic:'Db',scale:['Db','Eb','F','Gb','Ab','Bb','C']},{tonic:'Ab',scale:['Ab','Bb','C','Db','Eb','F','G']},{tonic:'Eb',scale:['Eb','F','G','Ab','Bb','C','D']},{tonic:'Bb',scale:['Bb','C','D','Eb','F','G','A']},{tonic:'F',scale:['F','G','A','Bb','C','D','E']}],minor:[{tonic:'C',scale:['C','D','Eb','F','G','Ab','Bb']},{tonic:'G',scale:['G','A','Bb','C','D','Eb','F']},{tonic:'D',scale:['D','E','F','G','A','Bb','C']},{tonic:'A',scale:['A','B','C','D','E','F','G']},{tonic:'E',scale:['E','F#','G','A','B','C','D']},{tonic:'B',scale:['B','C#','D','E','F#','G','A']},{tonic:'F#',scale:['F#','G#','A','B','C#','D','E']},{tonic:'C#',scale:['C#','D#','E','F#','G#','A','B']},{tonic:'G#',scale:['G#','A#','B','C#','D#','E','F#']},{tonic:'Eb',scale:['Eb','F','Gb','Ab','Bb','Cb','Db']},{tonic:'Bb',scale:['Bb','C','Db','Eb','F','Gb','Ab']},{tonic:'F',scale:['F','G','Ab','Bb','C','Db','Eb']}]};
const MODES={major:{qualities:['major','minor','minor','major','major','minor','diminished'],degrees:['I','ii','iii','IV','V','vi','vii°'],functions:['Tónica','Supertónica','Mediante','Subdominante','Dominante','Superdominante','Sensible'],label:'mayor',eyebrow:'Escala natural mayor',pattern:'<strong>Patrón fijo:</strong> I, IV y V son mayores; ii, iii y vi son menores; vii° es disminuido.'},minor:{qualities:['minor','diminished','major','minor','minor','major','major'],degrees:['i','ii°','III','iv','v','VI','VII'],functions:['Tónica','Supertónica','Mediante','Subdominante','Dominante menor','Submediante','Subtónica'],label:'menor natural',eyebrow:'Escala menor natural',pattern:'<strong>Patrón fijo:</strong> i, iv y v son menores; III, VI y VII son mayores; ii° es disminuido.'}};
const PC={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,Fb:4,'E#':5,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11,Cb:11},SHARP=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],FLAT=['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'],LATIN={C:'DO',D:'RE',E:'MI',F:'FA',G:'SOL',A:'LA',B:'SI'};
const OPEN={'C:major':[null,3,2,0,1,0],'G:major':[3,2,0,0,0,3],'D:major':[null,null,0,2,3,2],'A:major':[null,0,2,2,2,0],'E:major':[0,2,2,1,0,0],'A:minor':[null,0,2,2,1,0],'E:minor':[0,2,2,0,0,0],'D:minor':[null,null,0,2,3,1]};
const state={mode:'major',keyIndex:0,nomenclature:'latin',instrument:'piano',selectedDegree:0,inversion:0,guitarVoicing:0,theme:localStorage.getItem('circulos-theme')||'system',progression:[]};
const el=Object.fromEntries(['toneSelector','scaleEyebrow','scaleTitle','scalePattern','chordsTitle','diatonicGrid','selectedDegreeLabel','selectedChordTitle','selectedChordNotes','pianoKeyboard','pianoVoicingText','guitarVoicings','pianoPanel','guitarPanel','statusKey','statusChord','statusPosition','themeBtn','playChordBtn','customProgression','applyProgressionBtn','playProgressionBtn','progressionChips','tempoInput','toast'].map(id=>[id,document.getElementById(id)]));
let progressionTimer=null;const keys=()=>KEYSETS[state.mode],mode=()=>MODES[state.mode],key=()=>keys()[state.keyIndex],notePc=n=>PC[n],selectedChord=()=>buildChords()[state.selectedDegree];
const formatNote=n=>state.nomenclature==='english'?n.replace('#','♯').replace('b','♭'):`${LATIN[n[0]]||n[0]}${n.slice(1).replace('#','♯').replace('b','♭')}`;const qualityLabel=q=>q==='major'?'Mayor':q==='minor'?'Menor':'Disminuido';const chordSymbol=c=>c.quality==='minor'?`${formatNote(c.root)}m`:c.quality==='diminished'?`${formatNote(c.root)}°`:formatNote(c.root);const chordLongName=c=>`${formatNote(c.root)} ${qualityLabel(c.quality).toLowerCase()}`;const chordIntervals=q=>q==='major'?[0,4,7]:q==='minor'?[0,3,7]:[0,3,6];const chromaticName=(pc,flat=false)=>(flat?FLAT:SHARP)[(pc+12)%12];
function buildChords(){const k=key(),m=mode();return k.scale.map((root,i)=>({root,rootPc:notePc(root),quality:m.qualities[i],degree:m.degrees[i],functionName:m.functions[i],notes:[k.scale[i],k.scale[(i+2)%7],k.scale[(i+4)%7]]}))}
function renderToneSelector(){el.toneSelector.innerHTML=keys().map((k,i)=>`<button class="tone-btn ${i===state.keyIndex?'active':''}" data-k="${i}" type="button">${formatNote(k.tonic)}</button>`).join('');el.toneSelector.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.keyIndex=Number(b.dataset.k);state.selectedDegree=state.inversion=state.guitarVoicing=0;renderAll()})}
function renderScale(){el.scaleEyebrow.textContent=mode().eyebrow;el.scaleTitle.textContent=`Escala de ${formatNote(key().tonic)} ${mode().label}`;el.scalePattern.innerHTML=mode().pattern}
function renderChords(){const chords=buildChords();el.chordsTitle.textContent=`Los 7 acordes de ${formatNote(key().tonic)} ${mode().label}`;el.diatonicGrid.innerHTML=chords.map((c,i)=>`<button class="chord-card ${i===state.selectedDegree?'active':''}" data-d="${i}" type="button"><span class="badge">${c.degree}</span><span class="play-dot"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7Z"/></svg></span><strong class="chord-name">${chordSymbol(c)}</strong><span class="chord-quality">${qualityLabel(c.quality)}</span><span class="chord-function">${c.functionName}</span><span class="chord-notes">${c.notes.map(formatNote).join(' · ')}</span></button>`).join('');el.diatonicGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.selectedDegree=Number(b.dataset.d);state.inversion=state.guitarVoicing=0;renderAll();playSelectedChord()})}
function pianoVoicingMidi(ch,inversion=state.inversion){const notes=chordIntervals(ch.quality).map(i=>60+ch.rootPc+i);while(notes[0]>=72)notes.forEach((_,i)=>notes[i]-=12);for(let i=0;i<inversion;i++)notes.push(notes.shift()+12);return notes}
function buildPiano(){const ch=selectedChord(),voicing=pianoVoicingMidi(ch),voicingSet=new Set(voicing),chordPcs=new Set(ch.notes.map(notePc)),rootPc=ch.rootPc,whitePcs=new Set([0,2,4,5,7,9,11]),labels=state.nomenclature==='latin'?['DO','DO♯','RE','RE♯','MI','FA','FA♯','SOL','SOL♯','LA','LA♯','SI']:['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];const start=48,end=84,whites=[];for(let midi=start;midi<=end;midi++)if(whitePcs.has(midi%12))whites.push(midi);const w=cssPx('--key-w',58),pad=parseFloat(getComputedStyle(el.pianoKeyboard).paddingLeft)||0;el.pianoKeyboard.innerHTML='';whites.forEach((midi,index)=>{const pc=midi%12;const keyBtn=document.createElement('button');keyBtn.type='button';keyBtn.className=`white-key${chordPcs.has(pc)?' chord-tone':''}${voicingSet.has(midi)?' voicing-tone':''}${pc===rootPc?' root-tone':''}`;keyBtn.textContent=labels[pc];keyBtn.onclick=()=>playMidi([midi],.7);el.pianoKeyboard.appendChild(keyBtn);if([0,2,5,7,9].includes(pc)&&midi+1<=end){const bm=midi+1,bpc=bm%12,black=document.createElement('button');black.type='button';black.className=`black-key${chordPcs.has(bpc)?' chord-tone':''}${voicingSet.has(bm)?' voicing-tone':''}${bpc===rootPc?' root-tone':''}`;black.style.left=`${pad+(index+1)*w}px`;black.textContent=labels[bpc];black.onclick=()=>playMidi([bm],.7);el.pianoKeyboard.appendChild(black)}});el.pianoKeyboard.style.minWidth=`${whites.length*w+8}px`;el.pianoVoicingText.textContent=voicing.map(m=>formatNote(chromaticName(m%12,key().tonic.includes('b')))).join(' · ');document.querySelectorAll('[data-inversion]').forEach(btn=>btn.classList.toggle('active',Number(btn.dataset.inversion)===state.inversion))}
const openVoicingFor=ch=>OPEN[`${ch.root}:${ch.quality}`]?{name:'Abierto tradicional',description:`Forma abierta de ${chordLongName(ch)}`,frets:OPEN[`${ch.root}:${ch.quality}`]}:null;const normalizeFret=f=>f===0?12:f;
function diminishedVoicings(ch){const rA=normalizeFret((ch.rootPc-9+12)%12);let rD=normalizeFret((ch.rootPc-2+12)%12);if(rD<4)rD+=12;return[{name:'Triada móvil',description:`Raíz en 5.ª cuerda · traste ${rA}`,frets:[null,rA,rA+1,rA+2,rA+1,null]},{name:'Triada aguda',description:`Raíz en 4.ª cuerda · traste ${rD}`,frets:[null,null,rD,rD-2,rD-3,rD-2]}]}
function barreVoicings(ch){if(ch.quality==='diminished')return diminishedVoicings(ch);const rE=normalizeFret((ch.rootPc-4+12)%12),rA=normalizeFret((ch.rootPc-9+12)%12),maj=ch.quality==='major',eShape=maj?[rE,rE+2,rE+2,rE+1,rE,rE]:[rE,rE+2,rE+2,rE,rE,rE],aShape=maj?[null,rA,rA+2,rA+2,rA+2,rA]:[null,rA,rA+2,rA+2,rA+1,rA];return[{name:'Cejilla · forma E',description:`Raíz en 6.ª cuerda · traste ${rE}`,frets:eShape,barre:{fret:rE,from:0,to:5}},{name:'Cejilla · forma A',description:`Raíz en 5.ª cuerda · traste ${rA}`,frets:aShape,barre:{fret:rA,from:1,to:5}}]}
function compactTriads(ch){const target=new Set(chordIntervals(ch.quality).map(i=>(ch.rootPc+i)%12)),tuning=[7,11,4],found=[];for(let g=0;g<=12;g++)for(let b=0;b<=12;b++)for(let e=0;e<=12;e++){const frets=[g,b,e],pcs=frets.map((f,i)=>(tuning[i]+f)%12);if(!pcs.every(pc=>target.has(pc))||new Set(pcs).size!==3)continue;const span=Math.max(...frets)-Math.min(...frets);if(span>4)continue;found.push({frets,span,min:Math.min(...frets),max:Math.max(...frets)})}found.sort((a,b)=>(a.span-b.span)||(a.max-b.max));const chosen=[];for(const item of found){if(chosen.some(c=>Math.abs(c.min-item.min)<3))continue;chosen.push(item);if(chosen.length===2)break}return chosen.map((item,i)=>({name:`Triada compacta ${i+1}`,description:`Tres cuerdas agudas · zona del traste ${Math.max(1,item.min)}`,frets:[null,null,null,...item.frets]}))}
function guitarVoicingsFor(ch){const result=[],open=openVoicingFor(ch);if(open)result.push(open);result.push(...barreVoicings(ch));result.push(...compactTriads(ch).slice(0,open?1:2));return result.slice(0,4)}const guitarMidi=v=>v.frets.map((f,i)=>f===null?null:[40,45,50,55,59,64][i]+f).filter(Number.isFinite);
function diagramSvg(v,ch){const frets=v.frets,positive=frets.filter(f=>Number.isFinite(f)&&f>0);let startFret=positive.length?Math.min(...positive):1;if(startFret<=3&&Math.max(...positive,0)<=5)startFret=1;const endFret=startFret+4,w=220,h=250,left=35,top=38,stringGap=30,fretGap=36,rootPc=ch.rootPc,tuningPc=[4,9,2,7,11,4];let svg=`<svg class="chord-diagram" viewBox="0 0 ${w} ${h}" role="img" aria-label="Diagrama de ${chordLongName(ch)}">`;for(let s=0;s<6;s++)svg+=`<line class="diagram-string" x1="${left+s*stringGap}" y1="${top}" x2="${left+s*stringGap}" y2="${top+5*fretGap}"/>`;for(let f=0;f<=5;f++)svg+=`<line class="${startFret===1&&f===0?'diagram-nut':'diagram-fret'}" x1="${left}" y1="${top+f*fretGap}" x2="${left+5*stringGap}" y2="${top+f*fretGap}"/>`;if(startFret>1)svg+=`<text class="diagram-label" x="8" y="${top+fretGap*.7}">${startFret}</text>`;if(v.barre&&v.barre.fret>=startFret&&v.barre.fret<=endFret){const y=top+(v.barre.fret-startFret+.5)*fretGap;svg+=`<line class="diagram-barre" x1="${left+v.barre.from*stringGap}" y1="${y}" x2="${left+v.barre.to*stringGap}" y2="${y}"/>`}frets.forEach((fret,s)=>{const x=left+s*stringGap;if(fret===null){svg+=`<text class="diagram-label" x="${x}" y="22" text-anchor="middle">×</text>`;return}if(fret===0){svg+=`<text class="diagram-label" x="${x}" y="22" text-anchor="middle">○</text>`;return}if(fret<startFret||fret>endFret)return;const y=top+(fret-startFret+.5)*fretGap,pc=(tuningPc[s]+fret)%12,cls=pc===rootPc?'diagram-root':'diagram-dot';svg+=`<circle class="${cls}" cx="${x}" cy="${y}" r="10"/>`;if(pc===rootPc)svg+=`<text class="diagram-dot-text" x="${x}" y="${y}">R</text>`});svg+=`<text class="diagram-label" x="${left}" y="${h-10}">6.ª</text><text class="diagram-label" x="${left+5*stringGap}" y="${h-10}" text-anchor="end">1.ª</text></svg>`;return svg}
function renderGuitar(){const ch=selectedChord(),voicings=guitarVoicingsFor(ch);if(state.guitarVoicing>=voicings.length)state.guitarVoicing=0;el.guitarVoicings.innerHTML=voicings.map((v,i)=>`<article class="voicing-card ${i===state.guitarVoicing?'active':''}" data-v="${i}"><div class="voicing-head"><div><h4>${v.name}</h4><p>${v.description}</p></div><button class="voicing-play" data-play="${i}" type="button" aria-label="Probar esta posición"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7Z"/></svg></button></div>${diagramSvg(v,ch)}</article>`).join('');el.guitarVoicings.querySelectorAll('.voicing-card').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('.voicing-play'))return;state.guitarVoicing=Number(card.dataset.v);renderGuitar();updateStatus()}));el.guitarVoicings.querySelectorAll('[data-play]').forEach(btn=>btn.addEventListener('click',()=>{state.guitarVoicing=Number(btn.dataset.play);renderGuitar();updateStatus();playMidi(guitarMidi(voicings[state.guitarVoicing]),1.15,true)}))}
function renderSelectedChord(){const ch=selectedChord();el.selectedDegreeLabel.textContent=`Grado ${ch.degree} · ${ch.functionName}`;el.selectedChordTitle.textContent=chordLongName(ch);el.selectedChordNotes.textContent=`Notas: ${ch.notes.map(formatNote).join(' · ')}`;buildPiano();renderGuitar()}
function setInstrument(inst){state.instrument=inst;document.querySelectorAll('[data-instrument]').forEach(btn=>btn.classList.toggle('active',btn.dataset.instrument===inst));el.pianoPanel.classList.toggle('hidden',inst!=='piano');el.guitarPanel.classList.toggle('hidden',inst!=='guitar');updateStatus()}
function updateStatus(){const ch=selectedChord();el.statusKey.textContent=`${formatNote(key().tonic)} ${mode().label}`;el.statusChord.textContent=chordLongName(ch);el.statusPosition.textContent=state.instrument==='piano'?['Fundamental','1.ª inversión','2.ª inversión'][state.inversion]:(guitarVoicingsFor(ch)[state.guitarVoicing]?.name||'Guitarra')}
function cssPx(name,fallback){const raw=getComputedStyle(document.documentElement).getPropertyValue(name).trim();const value=parseFloat(raw);return Number.isFinite(value)&&value>0?value:fallback;}

function playMidi(midis,duration=1,arpeggio=false){window.CirculosAudio?.play(midis,state.instrument==='guitar'?'guitar':'piano',{arpeggio});}

function playSelectedChord(){const ch=selectedChord();if(state.instrument==='guitar'){const v=guitarVoicingsFor(ch)[state.guitarVoicing];playMidi(guitarMidi(v),1.2,true)}else playMidi(pianoVoicingMidi(ch),1.2)}
function parseChordToken(token){let raw=token.trim().replace(/[–—,;|]+/g,'').replace(/♯/g,'#').replace(/♭/g,'b');if(!raw)return null;const upper=raw.toUpperCase(),latinRoots=[['SOL','G'],['DO','C'],['RE','D'],['MI','E'],['FA','F'],['LA','A'],['SI','B']];let root=null,rest=raw;for(const[latin,english]of latinRoots){if(upper.startsWith(latin)){root=english;rest=raw.slice(latin.length);break}}if(!root){const match=raw.match(/^([A-Ga-g])([#b]?)(.*)$/);if(!match)return null;root=match[1].toUpperCase()+match[2];rest=match[3]}else if(/^[#b]/.test(rest)){root+=rest[0];rest=rest.slice(1)}if(!(root in PC))return null;const suffix=rest.toLowerCase(),quality=suffix.includes('dim')||suffix.includes('°')||suffix==='o'?'diminished':suffix.startsWith('m')?'minor':'major',preferFlat=root.includes('b');return{root,rootPc:notePc(root),quality,degree:'',functionName:'Progresión libre',notes:chordIntervals(quality).map(i=>chromaticName(notePc(root)+i,preferFlat))}}
function applyProgression(showMessage=true){const tokens=el.customProgression.value.split(/\s+/).map(parseChordToken).filter(Boolean);if(!tokens.length){showToast('No pude reconocer los acordes. Prueba: DO LAm FA SOL');return}state.progression=tokens;renderProgression();if(showMessage)showToast(`${tokens.length} acordes preparados`)}
const renderProgression=(a=-1)=>el.progressionChips.innerHTML=state.progression.map((c,i)=>`<span class="progression-chip ${i===a?'playing':''}">${chordSymbol(c)}</span>`).join('');
function playProgression(){if(!state.progression.length)applyProgression(false);if(!state.progression.length)return;const textNode=el.playProgressionBtn.querySelector('span');if(progressionTimer){clearInterval(progressionTimer);progressionTimer=null;renderProgression();textNode.textContent='Reproducir';return}const bpm=Math.min(220,Math.max(40,Number(el.tempoInput.value)||92)),beatMs=60000/bpm*2;let i=0;const tick=()=>{const ch=state.progression[i];renderProgression(i);playMidi(pianoVoicingMidi(ch,0),Math.min(1.4,beatMs/1000*.8));i++;if(i>=state.progression.length){setTimeout(()=>renderProgression(),beatMs*.75);clearInterval(progressionTimer);progressionTimer=null;textNode.textContent='Reproducir'}};textNode.textContent='Detener';tick();progressionTimer=setInterval(tick,beatMs)}
function applyTheme(){const resolved=state.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):state.theme;document.documentElement.dataset.theme=resolved;document.querySelector('meta[name="theme-color"]').setAttribute('content',resolved==='dark'?'#101110':'#f5f5f2')}
function cycleTheme(){state.theme=state.theme==='system'?'light':state.theme==='light'?'dark':'system';localStorage.setItem('circulos-theme',state.theme);applyTheme();showToast(`Apariencia: ${state.theme==='system'?'sistema':state.theme==='light'?'clara':'oscura'}`)}
function showToast(msg){el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.toast.classList.remove('show'),1900)}
function renderAll(){renderToneSelector();renderScale();renderChords();renderSelectedChord();setInstrument(state.instrument);updateStatus()}
document.querySelectorAll('[data-nomenclature]').forEach(btn=>btn.addEventListener('click',()=>{state.nomenclature=btn.dataset.nomenclature;document.querySelectorAll('[data-nomenclature]').forEach(i=>i.classList.toggle('active',i===btn));renderAll();renderProgression()}));document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{state.mode=btn.dataset.mode;state.keyIndex=0;state.selectedDegree=0;state.inversion=0;state.guitarVoicing=0;document.querySelectorAll('[data-mode]').forEach(i=>i.classList.toggle('active',i===btn));renderAll()}));document.querySelectorAll('[data-instrument]').forEach(btn=>btn.addEventListener('click',()=>setInstrument(btn.dataset.instrument)));document.querySelectorAll('[data-inversion]').forEach(btn=>btn.addEventListener('click',()=>{state.inversion=Number(btn.dataset.inversion);buildPiano();updateStatus();playSelectedChord()}));document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(i=>i.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})}));document.getElementById('scrollTopBtn').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));el.themeBtn.addEventListener('click',cycleTheme);el.playChordBtn.addEventListener('click',playSelectedChord);el.applyProgressionBtn.addEventListener('click',()=>applyProgression());el.customProgression.addEventListener('keydown',e=>{if(e.key==='Enter')applyProgression()});el.playProgressionBtn.addEventListener('click',playProgression);matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.theme==='system')applyTheme()});applyTheme();applyProgression(false);renderAll();})();
